<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Über uns',
    'Body' => 'Inhalt',
    'Check your email for further instructions.' => 'Bitte prüfen Sie Ihre Email für weitere Anweisungen.',
    'Contact' => 'Kontakt',
    'Email' => 'Email',
    'Home' => 'Home',
    'If you forgot your password you can' => 'Wenn Sie ihr Passwort vergessen haben, können Sie',
    'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => 'Wenn Sie irgendwelche Fragen oder Anregungen haben, dann füllen Sie bitte die Maske unten aus, um uns zu kontaktieren. Vielen Dank.',
    'Login' => 'Anmelden',
    'Logout' => 'Abmelden',
    'Name' => 'Name',
    'New password saved.' => 'Das neue Passwurde wurde gespeichert',
    'Password' => 'Passwort',
    'Please choose your new password:' => 'Bitte wählen Sie ihr neues Passwort:',
    'Please fill out the following fields to login:' => 'Bitte füllen Sie die folgenden Felder für die Anmeldung aus:',
    'Please fill out the following fields to signup:' => 'Bitte füllen Sie die folgenden Felder für die Registrierung aus:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Bitte geben Sie ihre hinterlegte Emailadresse an. Eine Mail zum Zurücksetzen des Passwort wird dann an diese Emailadresse verschickt.',
    'Request password reset' => 'Anfordern einer Passwort&shy;rücksetzung',
    'Reset password' => 'Zurücksetzen des Passworts',
    'Send' => 'Verschicken',
    'Signup' => 'Registrieren',
    'Sorry, we are unable to reset password for the provided email address.' => 'Leider konnten wir das Passwort für die angegebene Emailadresse nicht zurücksetzen',
    'Subject' => 'Betreff',
    'Submit' => 'Abschicken',
    'Terms accepted' => 'Bedingungen anerkannt',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Vielen Dank für Ihre Kontaktaufnahme. Wir werden so schnell wie möglich antworten und haben auch Ihnen die Mail für Ihre Unterlagen geschickt.',
    'There is no user with this email address.' => 'Es gibt keinen Nutzer mit dieser Emailadresse',
    'There was an error sending your message.' => 'Es gab beim Versenden der Email leider einen Fehler.',
    'This email address has already been taken.' => 'Diese Emailadresse ist bereits in Verwendung',
    'This user name has already been taken.' => 'Dieser Benutzername ist bereits in Verwendung',
    'This user name is reserved.' => 'Dieser Benutzername ist reserviert',
    'Username' => 'Benutzername',
    'Verification Code' => 'Prüfcode',
    'You need to accept the terms.' => 'Sie müssen die Bedingungen anerkennen.',
    'reset it' => 'es zurücksetzen',
];
