<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Administrator' => 'Administrator',
  'Anonymous User' => 'Anonymer Nutzer',
  'Email' => 'Email',
  'Guest' => 'Gast',
  'Guest access' => 'Gastzugang',
  'Incorrect username or password.' => 'Falscher Benutzername oder falsches Passwort.',
  'Password' => 'Passwort',
  'Remember me' => 'An mich erinnern',
  'Terms accepted' => 'Bedingungen anerkannt',
  'There is no user with such email.' => 'Es gibt keinen Nutzer mit dieser Emailadresse',
  'This email address has already been taken.' => 'Diese Emailadresse ist bereits in Verwendung',
  'This user name has already been taken.' => 'Dieser Benutzername ist bereits in Verwendung',
  'This user name is reserved.' => 'Dieser Benutzername ist reserviert',
  'User' => 'Nutzer',
  'Username' => 'Benutzername',
  'You are not authorized to perform this action' => 'Sie sind für die Operation nicht berechtigt.',
  'You need to accept the terms.' => 'Sie müssen die Bedingungen anerkennen.',
);
